# Generated by Django 4.0.4 on 2022-04-28 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BugDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('screen_shoot', models.ImageField(blank=True, null=True, upload_to='uploads/% Y/% m/% d/')),
                ('importance_level', models.CharField(choices=[('pending', 'Waiting for set'), ('low', 'Low'), ('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical'), ('blocker', 'Blocker')], default='Not set...', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SolvingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in progress', 'Working on a problem'), ('not touched', 'Not reviewed'), ('resolved', 'Bug fixed')], default='Pending...', max_length=30)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bug_report.bugdescription')),
            ],
        ),
    ]
